name: startup_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavorizr: ^2.2.3
  google_fonts: ^6.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#android:
#  flavorDimensions: "environment"
#  productFlavors:
#    dev:
#      dimension: "environment"
#      applicationId: "com.dartKnightRises.startupApp.dev"
#      # Add any other Android-specific configurations here
#    staging:
#      dimension: "environment"
#      applicationId: "com.dartKnightRises.startupApp.staging"
#      # Add any other Android-specific configurations here
#    prod:
#      dimension: "environment"
#      applicationId: "com.dartKnightRises.startupApp.prod"
#      # Add any other Android-specific configurations here
#
#ios:
#  flavorDimensions: "environment"
#  target:
#    'dev':
#    # Add any iOS-specific configurations here
#    'staging':
#    # Add any iOS-specific configurations here
#    'prod':
#    # Add any iOS-specific configurations here
